[features]
seeds = false
skip-lint = false
[programs.devnet]
creator_rent = "5Fq8padZgVoCsLBE5N6RsAmmJVpwRRqLVD6ysX36pjsS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./owner-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deleteCollection = "ts-node ./cli/deleteCollection.ts"
